### ISSUE TITLE
Yify most popular - no covers on some movies

### ISSUE THREAD

**Issue by escape75** [jmarth/plugin.video.kmediatorrent#86]
Missing cover art on "Interstellar" and "Imitation Game" for example,
but yet the covers show up fine in xbmctorrent using same scraper.

**Comment by jmarth** [comment]
Strange the information shows for me but I just cleared my catch and now its not showing. I will look into it. Thanks for finding this.

**Comment by tomtomclub** [comment]
same here thanks jmarth also the scrapers are not translated

**Comment by gadudi** [comment]
Same problem here, for some reason, since Yify moved from http://yts.re to http://yts.to, I don't get the movies covers at all.
from what I understand, they changed the movies covers location. for instance, for the movie "The Fault in Our Stars": the movie URL is: "http://yts.to/movie/the-fault-in-our-stars-2014". the cover URL is: "http://s.ynet.io/assets/images/movies/The_Fault_in_Our_Stars_2014/medium-cover.jpg".
Do you think there is a workarond?

**Comment by jmarth** [comment]
I would need need to fix this or someone can do it themselves in the yify scrapper. I most likely wont be able to fix this for a couple of weeks.

**Comment by escape75** [comment]
Update, seems to be an issue with tmdb, I don't know if that's something the plugin uses or relies
on kodi to pull the info down, tried installing the Universal Movie Scraper but still no luck. Weird.

**Comment by escape75** [comment]
Update 2, the issue is with double slashes ...

http://image.tmdb.org/t/p//w500//dM2w364MScsjFf8pfMbaWUcWrR.jpg     no workie.
http://image.tmdb.org/t/p/w500/dM2w364MScsjFf8pfMbaWUcWrR.jpg      all good.

**Comment by tomtomclub** [comment]
It is only on TV series and with  the skin skin.aeon.shednox.helix

**Comment by escape75** [comment]
I get it with default skin on movies (the issue),- clear your cache, maybe they're cached.
Or maybe the issue only happens in openelec but seems like a plugin issue to me ...

**Comment by escape75** [comment]
Fixed in latest merge.
